//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miller {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected miller0061072133.Partials.header1 header;
		
		protected miller0061072133.Partials.header nav1;
		
		protected System.Web.UI.WebControls.Button btnBack;
		
		protected System.Web.UI.WebControls.Xml Xml1;
		
		protected System.Web.UI.WebControls.Xml Xml2;
		
		protected miller0061072133.Partials.footer footer1;
	}
}
